from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://zxfw.court.gov.cn/zxfw/")
    page.goto("https://zxfw.court.gov.cn/zxfw/#/")
    page.goto("https://zxfw.court.gov.cn/zxfw/#/pagesGrxx/pc/login/index")
    page.locator("uni-input").filter(has_text="请输入手机号/居民身份证号").get_by_role("textbox").click()
    page.get_by_text("律师用户").click()
    page.locator("uni-input").filter(has_text="请输入手机号/居民身份证号").get_by_role("textbox").click()
    page.locator("uni-input").filter(has_text="请输入手机号/居民身份证号").get_by_role("textbox").fill("13723715831")
    page.locator("input[type=\"password\"]").click()
    page.locator("input[type=\"password\"]").click()
    page.locator("input[type=\"password\"]").fill("HU1234pp")
    page.locator("uni-input").filter(has_text="请输入验证码").get_by_role("textbox").click()
    page.locator("uni-input").filter(has_text="请输入验证码").get_by_role("textbox").fill("wmkr")
    page.get_by_text("登录", exact=True).click()
    page.get_by_text("在线立案").click()
    with page.expect_popup() as page1_info:
        page.locator("uni-view").filter(has_text=re.compile(r"^保全在线保全$")).locator("uni-view").nth(3).click()
    page1 = page1_info.value
    page1.get_by_role("radio", name="我已阅读网上保全须知").click()
    page1.get_by_role("button", name="创建保全申请").click()
    page1.get_by_placeholder("选择申请法院").click()
    page1.get_by_placeholder("选择申请法院").fill("广东")
    page1.get_by_text("广东省深圳市中级人民法院").click()
    page1.get_by_placeholder("请输入您要申请的保全金额").click()
    page1.get_by_placeholder("请输入您要申请的保全金额").fill("2,0000")
    page1.get_by_role("radio", name="律师").click()
    page1.get_by_role("button", name="创建保全").click()
    page1.get_by_text("添加").first.click()
    page1.locator("div").filter(has_text=re.compile(r"^姓名$")).get_by_role("textbox").click()
    page1.locator("div").filter(has_text=re.compile(r"^姓名$")).get_by_role("textbox").fill("李小二")
    page1.locator("div").filter(has_text=re.compile(r"^证件号码$")).get_by_role("textbox").click()
    page1.locator("div").filter(has_text=re.compile(r"^证件号码$")).get_by_role("textbox").fill("445202199603060317")
    page1.get_by_text("姓名 国别或地区中国中国香港中国澳门中国台湾省美国俄罗斯加拿大日本英国法国德国意大利爱尔兰荷兰比利时卢森堡西班牙葡萄牙希腊瑞典芬兰奥地利丹麦波兰马耳他斯洛文尼亚").click()
    page1.get_by_placeholder("选择日期").click()
    page1.get_by_text("姓名 国别或地区中国中国香港中国澳门中国台湾省美国俄罗斯加拿大日本英国法国德国意大利爱尔兰荷兰比利时卢森堡西班牙葡萄牙希腊瑞典芬兰奥地利丹麦波兰马耳他斯洛文尼亚").click()
    page1.locator("form div").filter(has_text="证件号码 证件号码输入有误").get_by_role("textbox").click()
    page1.locator("form div").filter(has_text="证件号码 证件号码输入有误").get_by_role("textbox").press("ArrowLeft")
    page1.locator("form div").filter(has_text="证件号码 证件号码输入有误").get_by_role("textbox").press("ArrowLeft")
    page1.locator("form div").filter(has_text="证件号码 证件号码输入有误").get_by_role("textbox").press("ArrowLeft")
    page1.locator("form div").filter(has_text="证件号码 证件号码输入有误").get_by_role("textbox").press("ArrowLeft")
    page1.locator("form div").filter(has_text="证件号码 证件号码输入有误").get_by_role("textbox").press("ArrowLeft")
    page1.locator("form div").filter(has_text="证件号码 证件号码输入有误").get_by_role("textbox").press("ArrowLeft")
    page1.locator("form div").filter(has_text="证件号码 证件号码输入有误").get_by_role("textbox").press("ArrowLeft")
    page1.locator("form div").filter(has_text="证件号码 证件号码输入有误").get_by_role("textbox").press("ArrowLeft")
    page1.locator("form div").filter(has_text="证件号码 证件号码输入有误").get_by_role("textbox").fill("445202199403060317")
    page1.locator("div").filter(has_text=re.compile(r"^出生日期$")).locator("div").first.click()
    page1.get_by_text("性别").click()
    page1.get_by_role("radio", name="男性").click()
    page1.locator("#addSQR div").filter(has_text=re.compile(r"^手机号码$")).get_by_role("textbox").click()
    page1.locator("#addSQR div").filter(has_text=re.compile(r"^手机号码$")).get_by_role("textbox").fill("13149930995")
    page1.locator("div").filter(has_text=re.compile(r"^经常居住地$")).get_by_role("textbox").click()
    page1.locator("div").filter(has_text=re.compile(r"^经常居住地$")).get_by_role("textbox").fill("广东省深圳市南山区文德福花园3栋1102")
    page1.get_by_role("button", name="保存").click()
    page1.get_by_text("添加").nth(1).click()
    page1.locator("div").filter(has_text=re.compile(r"^姓名$")).get_by_role("textbox").click()
    page1.locator("div").filter(has_text=re.compile(r"^姓名$")).get_by_role("textbox").fill("李小三")
    page1.locator("div").filter(has_text=re.compile(r"^证件号码$")).get_by_role("textbox").click()
    page1.locator("div").filter(has_text=re.compile(r"^证件号码$")).get_by_role("textbox").fill("445202199403060518")
    page1.get_by_text("年龄").click()
    page1.locator("form div").filter(has_text="证件号码 证件号码输入有误").get_by_role("textbox").click()
    page1.locator("form div").filter(has_text="证件号码 证件号码输入有误").get_by_role("textbox").fill("445202199403060317")
    page1.get_by_role("radio", name="男性").click()
    page1.locator("#addBSQR div").filter(has_text=re.compile(r"^手机号码$")).get_by_role("textbox").click()
    page1.locator("#addBSQR div").filter(has_text=re.compile(r"^手机号码$")).get_by_role("textbox").fill("13631610603")
    page1.get_by_role("button", name="保存").click()
    page1.get_by_text("编辑").nth(1).click()
    page1.get_by_role("radio", name="法人", exact=True).click()
    page1.get_by_role("radio", name="非法人组织").click()
    page1.get_by_text("自然人 法人 非法人组织").click()
    page1.get_by_role("radio", name="自然人").click()
    page1.locator(".popover-title > .el-icon-close").click()
    page1.locator("span").filter(has_text=re.compile(r"^添加$")).click()
    page1.get_by_placeholder("请选择财产类型").click()
    page1.locator("li").filter(has_text="存款").click()
    page1.get_by_placeholder("请选择财产所有人").click()
    page1.locator("li").filter(has_text="李小三").click()
    page1.locator("div").filter(has_text=re.compile(r"^开户行所在地北京天津河北山西内蒙古辽宁吉林黑龙江上海江苏浙江安徽福建江西山东河南湖北湖南广东广西海南重庆四川贵州云南西藏陕西甘肃青海宁夏新疆$")).get_by_role("textbox").click()
    page1.get_by_text("广东", exact=True).click()
    page1.locator("div").filter(has_text=re.compile(r"^开户银行名称$")).get_by_role("textbox").click()
    page1.locator("div").filter(has_text=re.compile(r"^开户银行名称$")).get_by_role("textbox").fill("中国银行")
    page1.locator("div").filter(has_text=re.compile(r"^开户账号$")).get_by_role("textbox").click()
    page1.locator("div").filter(has_text=re.compile(r"^开户账号$")).get_by_role("textbox").fill("4325362362364342")
    page1.locator("div").filter(has_text=re.compile(r"^数额$")).get_by_role("textbox").click()
    page1.locator("div").filter(has_text=re.compile(r"^数额$")).get_by_role("textbox").fill("20,0000")
    page1.get_by_placeholder("请选择单位").click()
    page1.locator("li").filter(has_text="人民币").click()
    page1.get_by_text("温馨提示：若您未找到相应的财产类型或未明确具体的财产线索时，请选择【其他】 财产类型 财产所有人 开户行所在地 开户银行名称 开户账号 数额 币种 财产价值￥ ").click()
    page1.locator("form div").filter(has_text="财产价值￥ 元").get_by_role("textbox").click()
    page1.locator("form div").filter(has_text="财产价值￥ 元").get_by_role("textbox").fill("20,0000")
    page1.get_by_role("button", name="保存", exact=True).click()
    page1.get_by_role("button", name="下一步").click()
    page1.locator("span").filter(has_text="添加").locator("i").click()
    page1.get_by_placeholder("请选择").click()
    page1.locator("li").filter(has_text="提供保证人").click()
    page1.get_by_placeholder("请输入担保人").click()
    page1.get_by_placeholder("请输入担保人").fill("李小四")
    page1.get_by_placeholder("请输入担保名称").click()
    page1.get_by_placeholder("请输入担保名称").fill("现金")
    page1.locator("#addDBXX div").filter(has_text="担保价值 元").get_by_role("textbox").click()
    page1.locator("#addDBXX div").filter(has_text="担保价值 元").get_by_role("textbox").fill("20,0000")
    page1.get_by_role("button", name="保存").click()
    page1.get_by_role("button", name="下一步").click()
    page1.get_by_text("保全申请书 上传").click()
    page1.locator(".el-upload").first.set_input_files("01_保全申请书.pdf")
    page1.locator("span").filter(has_text="起诉状 上传").locator("i").click()
    page1.get_by_text("申请人-李小二-自然人 上传").click()
    page1.get_by_text("申请人-李小二-自然人 上传").set_input_files("03_申请人证照.pdf")
    page1.get_by_text("被申请人-李小三-自然人 上传").click()
    page1.get_by_text("被申请人-李小三-自然人 上传").set_input_files("04_被申请人身份证.pdf")
    page1.get_by_text("提供保证人-现金 上传").click()
    page1.get_by_text("提供保证人-现金 上传").set_input_files(["06_担保函.pdf", "07_保证人证照.pdf"])
    page1.get_by_text("案件证据及相关材料 上传").click()
    page1.locator("div:nth-child(6) > .fd-upload-wrap > .upload-demo > .el-upload").set_input_files("证据材料.doc")
    page1.get_by_text("其他材料 上传").click()
    page1.get_by_role("button", name="下一步").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
